### ISSUE TITLE
Error at startup when combining with storage-restservice-springboot

### ISSUE THREAD

**Issue by Flip012** [xdev-software/spring-data-eclipse-store#142]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/spring-data-eclipse-store/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/spring-data-eclipse-store/issues) or [closed](https://github.com/xdev-software/spring-data-eclipse-store/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

2.1.0

### Steps to reproduce the bug

1. Adding maven dependencies:

```
<dependency>
	<groupId>org.eclipse.store</groupId>
	<artifactId>storage-embedded</artifactId>
	<version>1.4.0</version>
</dependency>
<dependency>
	<groupId>org.eclipse.store</groupId>
	<artifactId>storage-restservice-springboot</artifactId>
	<version>1.4.0</version>
</dependency>
<dependency>
	<groupId>software.xdev</groupId>
	<artifactId>spring-data-eclipse-store</artifactId>
	<version>2.1.0</version>
</dependency>
```
2. Set property in application.properties: `org.eclipse.store.rest.enabled=true`
3. Run the application

### Expected behavior

REST servlet is reachable under http://localhost:8080>/store-data/

(see https://docs.eclipsestore.io/manual/storage/rest-interface/index.html)

### Actual behavior

Error appears at startup:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageRestAdapters' defined in class path resource [org/eclipse/store/storage/restservice/spring/boot/types/StoreDataRestAutoConfiguration.class]: Failed to instantiate [java.util.Map]: Factory method 'storageRestAdapters' threw exception with message: null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971) ~[spring-context-6.1.11.jar:6.1.11]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.11.jar:6.1.11]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.8.jar:3.2.8]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.8.jar:3.2.8]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.8.jar:3.2.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.2.8.jar:3.2.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.2.8.jar:3.2.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.2.8.jar:3.2.8]
	at org.vaadin.example.Application.main(Application.java:24) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'storageRestAdapters' threw exception with message: null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.11.jar:6.1.11]
	... 19 common frames omitted
Caused by: org.eclipse.store.storage.exceptions.StorageExceptionNotRunning: null
	at org.eclipse.store.storage.types.StorageSystem$Default.ensureRunning(StorageSystem.java:319) ~[storage-1.4.0.jar:na]
	at org.eclipse.store.storage.types.StorageSystem$Default.createRequestAcceptor(StorageSystem.java:696) ~[storage-1.4.0.jar:na]
	at org.eclipse.store.storage.embedded.types.EmbeddedStorageConnectionFoundation$Default.internalGetStorageRequestAcceptor(EmbeddedStorageConnectionFoundation.java:295) ~[storage-embedded-1.4.0.jar:na]
	at org.eclipse.store.storage.embedded.types.EmbeddedStorageConnectionFoundation$Default.createStorageConnection(EmbeddedStorageConnectionFoundation.java:349) ~[storage-embedded-1.4.0.jar:na]
	at org.eclipse.store.storage.embedded.types.EmbeddedStorageManager$Default.createConnection(EmbeddedStorageManager.java:459) ~[storage-embedded-1.4.0.jar:na]
	at org.eclipse.store.storage.embedded.types.EmbeddedStorageManager$Default.singletonConnection(EmbeddedStorageManager.java:142) ~[storage-embedded-1.4.0.jar:na]
	at org.eclipse.store.storage.embedded.types.EmbeddedStorageManager$Default.persistenceManager(EmbeddedStorageManager.java:203) ~[storage-embedded-1.4.0.jar:na]
	at org.eclipse.store.storage.restadapter.types.ViewerBinaryPersistenceManager.New(ViewerBinaryPersistenceManager.java:48) ~[storage-restadapter-1.4.0.jar:na]
	at org.eclipse.store.storage.restadapter.types.EmbeddedStorageRestAdapter.New(EmbeddedStorageRestAdapter.java:51) ~[storage-restadapter-1.4.0.jar:na]
	at org.eclipse.store.storage.restadapter.types.StorageRestAdapter.New(StorageRestAdapter.java:35) ~[storage-restadapter-1.4.0.jar:na]
	at org.eclipse.store.storage.restservice.spring.boot.types.StoreDataRestAutoConfiguration.lambda$storageRestAdapters$0(StoreDataRestAutoConfiguration.java:44) ~[storage-restservice-springboot-1.4.0.jar:na]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[na:na]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at org.eclipse.store.storage.restservice.spring.boot.types.StoreDataRestAutoConfiguration.storageRestAdapters(StoreDataRestAutoConfiguration.java:42) ~[storage-restservice-springboot-1.4.0.jar:na]
	at org.eclipse.store.storage.restservice.spring.boot.types.StoreDataRestAutoConfiguration$$SpringCGLIB$$0.CGLIB$storageRestAdapters$1(<generated>) ~[storage-restservice-springboot-1.4.0.jar:na]
	at org.eclipse.store.storage.restservice.spring.boot.types.StoreDataRestAutoConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[storage-restservice-springboot-1.4.0.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.11.jar:6.1.11]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348) ~[spring-context-6.1.11.jar:6.1.11]
	at org.eclipse.store.storage.restservice.spring.boot.types.StoreDataRestAutoConfiguration$$SpringCGLIB$$0.storageRestAdapters(<generated>) ~[storage-restservice-springboot-1.4.0.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.11.jar:6.1.11]
	... 20 common frames omitted
```
The application does not work / it does not start anymore.

**Comment by JohannesRabauer** [comment]
I have just analyzed the problem and i could reproduce your behavior.
Unfortunately i cannot produce a quick solution or a workaround for it. Since the Rest-Endpoint is not part of the EclipseStore-Core library, i changed the label to enhancement.
We will try to implement this feature as soon as possible.

**Comment by JohannesRabauer** [comment]
For future references: https://github.com/xdev-software/spring-data-eclipse-store/tree/%23142-springboot-restservice

**Comment by JohannesRabauer** [comment]
@Flip012 please check out the current version 2.4.1 and test the behavior again. It should be fixed, if you consider the documented code: https://spring-eclipsestore.xdev.software/features/rest-api.html

**Comment by JohannesRabauer** [comment]
Closing because there is no response.
