### ISSUE TITLE
HashSetTest compile error

### ISSUE THREAD

**Issue by rpx99** [xdev-software/spring-data-eclipse-store#15]
**tron$ mvn --version**
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /home/rpx/Downloads/apache-maven-3.9.6
Java version: 21.0.1, vendor: N/A, runtime: /usr/local/jdk-21
Default locale: en_US, platform encoding: UTF-8
OS name: "openbsd", version: "7.4", arch: "amd64", family: "unix"

**tron$ java --version**
openjdk 21.0.1 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-2)
OpenJDK 64-Bit Server VM (build 21.0.1+12-2, mixed mode, sharing)

_mvn clean install_ leads to a compile error:

**tron$ mvn clean install**               
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] spring-data-eclipse-store                                          [jar]
[INFO] spring-data-eclipse-store-demo                                     [jar]
[INFO] spring-data-eclipse-store-benchmark                                [jar]
[INFO] spring-data-eclipse-store-root                                     [pom]
[INFO] 
[INFO] --------------< software.xdev:spring-data-eclipse-store >---------------
[INFO] Building spring-data-eclipse-store 1.0.1-SNAPSHOT                  [1/4]
[INFO]   from spring-data-eclipse-store/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ spring-data-eclipse-store ---
[INFO] Deleting /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/target
[INFO] 
[INFO] --- license:4.3:format (first) @ spring-data-eclipse-store ---
[INFO] Updating license headers...
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ spring-data-eclipse-store ---
[INFO] Copying 3 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.12.1:compile (default-compile) @ spring-data-eclipse-store ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 74 source files with javac [debug release 17] to target/classes
[WARNING] unknown enum constant javax.annotation.meta.When.MAYBE
  reason: class file for javax.annotation.meta.When not found
[INFO] /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/src/main/java/software/xdev/spring/data/eclipse/store/repository/config/EclipseStoreRepositoryConfigurationExtension.java: /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/src/main/java/software/xdev/spring/data/eclipse/store/repository/config/EclipseStoreRepositoryConfigurationExtension.java uses or overrides a deprecated API.
[INFO] /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/src/main/java/software/xdev/spring/data/eclipse/store/repository/config/EclipseStoreRepositoryConfigurationExtension.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ spring-data-eclipse-store ---
[INFO] Copying 2 resources from src/test/resources to target/test-classes
[INFO] 
[INFO] --- compiler:3.12.1:testCompile (default-testCompile) @ spring-data-eclipse-store ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 79 source files with javac [debug release 17] to target/test-classes
[INFO] 
[INFO] --- surefire:3.2.5:test (default-test) @ spring-data-eclipse-store ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running software.xdev.spring.data.eclipse.store.integration.tests.HashSetTest
java(92809) in free(): bogus pointer (double free?) 0x8cd691da000
Abort trap (core dumped) 
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for spring-data-eclipse-store-root 1.0.1-SNAPSHOT:
[INFO] 
[INFO] spring-data-eclipse-store .......................... FAILURE [  7.310 s]
[INFO] spring-data-eclipse-store-demo ..................... SKIPPED
[INFO] spring-data-eclipse-store-benchmark ................ SKIPPED
[INFO] spring-data-eclipse-store-root ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.510 s
[INFO] Finished at: 2024-02-04T10:40:36+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project spring-data-eclipse-store: 
[ERROR] 
[ERROR] Please refer to /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store' && '/usr/local/jdk-21/bin/java' '--add-opens' 'java.base/java.util=ALL-UNNAMED' '--add-exports' 'java.base/jdk.internal.misc=ALL-UNNAMED' '-jar' '/home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/target/surefire/surefirebooter-20240204104032595_3.jar' '/home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/target/surefire' '2024-02-04T10-40-32_482-jvmRun1' 'surefire-20240204104032595_1tmp' 'surefire_0-20240204104032595_2tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] software.xdev.spring.data.eclipse.store.integration.tests.HashSetTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store' && '/usr/local/jdk-21/bin/java' '--add-opens' 'java.base/java.util=ALL-UNNAMED' '--add-exports' 'java.base/jdk.internal.misc=ALL-UNNAMED' '-jar' '/home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/target/surefire/surefirebooter-20240204104032595_3.jar' '/home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/target/surefire' '2024-02-04T10-40-32_482-jvmRun1' 'surefire-20240204104032595_1tmp' 'surefire_0-20240204104032595_2tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] software.xdev.spring.data.eclipse.store.integration.tests.HashSetTest
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1241)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1090)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:910)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Trying to "fix" it with _-DforkCount=0_ leads to an error, too:

tron$ **mvn clean install -DforkCount=0** 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] spring-data-eclipse-store                                          [jar]
[INFO] spring-data-eclipse-store-demo                                     [jar]
[INFO] spring-data-eclipse-store-benchmark                                [jar]
[INFO] spring-data-eclipse-store-root                                     [pom]
[INFO] 
[INFO] --------------< software.xdev:spring-data-eclipse-store >---------------
[INFO] Building spring-data-eclipse-store 1.0.1-SNAPSHOT                  [1/4]
[INFO]   from spring-data-eclipse-store/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ spring-data-eclipse-store ---
[INFO] Deleting /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/target
[INFO] 
[INFO] --- license:4.3:format (first) @ spring-data-eclipse-store ---
[INFO] Updating license headers...
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ spring-data-eclipse-store ---
[INFO] Copying 3 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.12.1:compile (default-compile) @ spring-data-eclipse-store ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 74 source files with javac [debug release 17] to target/classes
[WARNING] unknown enum constant javax.annotation.meta.When.MAYBE
  reason: class file for javax.annotation.meta.When not found
[INFO] /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/src/main/java/software/xdev/spring/data/eclipse/store/repository/config/EclipseStoreRepositoryConfigurationExtension.java: /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/src/main/java/software/xdev/spring/data/eclipse/store/repository/config/EclipseStoreRepositoryConfigurationExtension.java uses or overrides a deprecated API.
[INFO] /home/rpx/Downloads/spring-data-eclipse-store/spring-data-eclipse-store/src/main/java/software/xdev/spring/data/eclipse/store/repository/config/EclipseStoreRepositoryConfigurationExtension.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ spring-data-eclipse-store ---
[INFO] Copying 2 resources from src/test/resources to target/test-classes
[INFO] 
[INFO] --- compiler:3.12.1:testCompile (default-testCompile) @ spring-data-eclipse-store ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 79 source files with javac [debug release 17] to target/test-classes
[INFO] 
[INFO] --- surefire:3.2.5:test (default-test) @ spring-data-eclipse-store ---
[WARNING] useSystemClassLoader setting has no effect when not forking
[WARNING] The parameter forkCount should likely not be 0. Forking a JVM for tests improves test accuracy. Ensure to have a <forkCount> >= 1.
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] Running software.xdev.spring.data.eclipse.store.integration.tests.HashSetTest
java(97509) in free(): bogus pointer (double free?) 0xe1c89941000
Abort trap (core dumped)

**Comment by rpx99** [comment]
The problem is due to jdk 21. I tried with java 17 and I could compile it successfully.

tron$ java --version                          
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-1, mixed mode, sharing)

I think it is the bug folks from eclipse store already submitted: [https://bugs.openjdk.org/browse/JDK-8325173](https://bugs.openjdk.org/browse/JDK-8325173)

Did not try the lib itself yet, but I do not see a reason why it should not work on OpenBSD.
